# Generated by Django 4.1.1 on 2022-10-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_remove_profile_baground_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="socialmedia", name="Google_link",),
        migrations.AddField(
            model_name="socialmedia",
            name="Github_link",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="about", name="address", field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="about", name="long_bio", field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name="about",
            name="short_bio",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="education",
            name="institute",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="education",
            name="qualification",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="experience",
            name="company_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="personal",
            name="description",
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name="personal",
            name="link",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="personal",
            name="project_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="designation",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fullname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sefphotograph",
            name="link",
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name="sefphotograph",
            name="photo_caption",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sefphotograph",
            name="photo_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name_of_skill",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="Facbook_link",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="Instagram_link",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="Linkedin_link",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="webdevelopment",
            name="description",
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name="webdevelopment",
            name="link",
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name="webdevelopment",
            name="project_name",
            field=models.CharField(max_length=100),
        ),
    ]
